module.exports = {
    list: [
        "3M Company",
        "Abbott Laboratories",
        "AbbVie Inc.",
        "Abiomed",
        "Accenture",
        "Activision Blizzard",
        "Adobe Inc.",
        "Advanced Micro Devices",
        "Advance Auto Parts",
        "AES Corp",
        "Aflac",
        "Agilent Technologies",
        "Air Products & Chemicals",
        "Akamai Technologies",
        "Alaska Air Group",
        "Albemarle Corporation",
        "Alexandria Real Estate Equities",
        "Alexion Pharmaceuticals",
        "Align Technology",
        "Allegion",
        "Alliant Energy",
        "Allstate Corp",
        "Alphabet Inc. (Class A)",
        "Alphabet Inc. (Class C)",
        "Altria Group Inc",
        "Amazon.com Inc.",
        "Amcor plc",
        "Ameren Corp",
        "American Airlines Group",
        "American Electric Power",
        "American Express",
        "American International Group",
        "American Tower Corp.",
        "American Water Works",
        "Ameriprise Financial",
        "AmerisourceBergen",
        "Ametek",
        "Amgen Inc.",
        "Amphenol Corp",
        "Analog Devices, Inc.",
        "ANSYS, Inc.",
        "Anthem",
        "Aon plc",
        "A.O. Smith Corp",
        "APA Corporation",
        "Apple Inc.",
        "Applied Materials Inc.",
        "Aptiv PLC",
        "Archer-Daniels-Midland Co",
        "Arista Networks",
        "Arthur J. Gallagher & Co.",
        "Assurant",
        "AT&T Inc.",
        "Atmos Energy",
        "Autodesk Inc.",
        "Automatic Data Processing",
        "AutoZone Inc",
        "AvalonBay Communities",
        "Avery Dennison Corp",
        "Baker Hughes Co",
        "Ball Corp",
        "Bank of America Corp",
        "The Bank of New York Mellon",
        "Baxter International Inc.",
        "Becton Dickinson",
        "Berkshire Hathaway",
        "Best Buy Co. Inc.",
        "Bio-Rad Laboratories",
        "Biogen Inc.",
        "BlackRock",
        "Boeing Company",
        "Booking Holdings Inc",
        "BorgWarner",
        "Boston Properties",
        "Boston Scientific",
        "Bristol-Myers Squibb",
        "Broadcom Inc.",
        "Broadridge Financial Solutions",
        "Brown-Forman Corp.",
        "C. H. Robinson Worldwide",
        "Cabot Oil & Gas",
        "Cadence Design Systems",
        "Caesars Entertainment",
        "Campbell Soup",
        "Capital One Financial",
        "Cardinal Health Inc.",
        "Carmax Inc",
        "Carnival Corp.",
        "Carrier Global",
        "Catalent",
        "Caterpillar Inc.",
        "Cboe Global Markets",
        "CBRE Group",
        "CDW",
        "Celanese",
        "Centene Corporation",
        "CenterPoint Energy",
        "Cerner",
        "CF Industries Holdings Inc",
        "Charles Schwab Corporation",
        "Charter Communications",
        "Chevron Corp.",
        "Chipotle Mexican Grill",
        "Chubb Limited",
        "Church & Dwight",
        "Cigna",
        "Cincinnati Financial",
        "Cintas Corporation",
        "Cisco Systems",
        "Citigroup Inc.",
        "Citizens Financial Group",
        "Citrix Systems",
        "The Clorox Company",
        "CME Group Inc.",
        "CMS Energy",
        "Coca-Cola Company",
        "Cognizant Technology Solutions",
        "Colgate-Palmolive",
        "Comcast Corp.",
        "Comerica Inc.",
        "Conagra Brands",
        "ConocoPhillips",
        "Consolidated Edison",
        "Constellation Brands",
        "The Cooper Companies",
        "Copart Inc",
        "Corning Inc.",
        "Corteva",
        "Costco Wholesale Corp.",
        "Crown Castle",
        "CSX Corp.",
        "Cummins Inc.",
        "CVS Health",
        "D. R. Horton",
        "Danaher Corp.",
        "Darden Restaurants",
        "DaVita Inc.",
        "Deere & Co.",
        "Delta Air Lines Inc.",
        "Dentsply Sirona",
        "Devon Energy",
        "DexCom",
        "Diamondback Energy",
        "Digital Realty Trust Inc",
        "Discover Financial Services",
        "Discovery, Inc. (Series A)",
        "Discovery, Inc. (Series C)",
        "Dish Network",
        "Dollar General",
        "Dollar Tree",
        "Dominion Energy",
        "Domino's Pizza",
        "Dover Corporation",
        "Dow Inc.",
        "DTE Energy Co.",
        "Duke Energy",
        "Duke Realty Corp",
        "DuPont de Nemours Inc",
        "DXC Technology",
        "Eastman Chemical",
        "Eaton Corporation",
        "eBay Inc.",
        "Ecolab Inc.",
        "Edison Int'l",
        "Edwards Lifesciences",
        "Electronic Arts",
        "Emerson Electric Company",
        "Enphase Energy",
        "Entergy Corp.",
        "EOG Resources",
        "Equifax Inc.",
        "Equinix",
        "Equity Residential",
        "Essex Property Trust, Inc.",
        "Estée Lauder Companies",
        "Etsy",
        "Evergy",
        "Eversource Energy",
        "Everest Re Group Ltd.",
        "Exelon Corp.",
        "Expedia Group",
        "Expeditors",
        "Extra Space Storage",
        "Exxon Mobil Corp.",
        "F5 Networks",
        "Facebook, Inc.",
        "Fastenal Co",
        "Federal Realty Investment Trust",
        "FedEx Corporation",
        "Fidelity National Information Services",
        "Fifth Third Bancorp",
        "FirstEnergy Corp",
        "First Republic Bank",
        "Fiserv Inc",
        "FleetCor Technologies Inc",
        "FLIR Systems",
        "FMC Corporation",
        "Ford Motor Company",
        "Fortinet",
        "Fortive Corp",
        "Fortune Brands Home & Security",
        "Fox Corporation (Class A)",
        "Fox Corporation (Class B)",
        "Franklin Resources",
        "Freeport-McMoRan Inc.",
        "Gap Inc.",
        "Garmin Ltd.",
        "Gartner Inc",
        "Generac Holdings",
        "General Dynamics",
        "General Electric",
        "General Mills",
        "General Motors",
        "Genuine Parts",
        "Gilead Sciences",
        "Globe Life Inc.",
        "Global Payments Inc.",
        "Goldman Sachs Group",
        "Grainger (W.W.) Inc.",
        "Halliburton Co.",
        "Hanesbrands Inc",
        "Hartford Financial Svc.Gp.",
        "Hasbro Inc.",
        "HCA Healthcare",
        "Healthpeak Properties",
        "Henry Schein",
        "The Hershey Company",
        "Hess Corporation",
        "Hewlett Packard Enterprise",
        "Hilton Worldwide Holdings Inc",
        "HollyFrontier Corp",
        "Hologic",
        "Home Depot",
        "Honeywell Int'l Inc.",
        "Hormel Foods Corp.",
        "Host Hotels & Resorts",
        "Howmet Aerospace",
        "HP Inc.",
        "Humana Inc.",
        "Huntington Bancshares",
        "Huntington Ingalls Industries",
        "IDEX Corporation",
        "Idexx Laboratories",
        "IHS Markit",
        "Illinois Tool Works",
        "Illumina Inc",
        "Incyte",
        "Ingersoll Rand",
        "Intel Corp.",
        "Intercontinental Exchange",
        "International Business Machines",
        "International Paper",
        "Interpublic Group",
        "International Flavors & Fragrances",
        "Intuit Inc.",
        "Intuitive Surgical Inc.",
        "Invesco Ltd.",
        "IPG Photonics Corp.",
        "IQVIA Holdings Inc.",
        "Iron Mountain Incorporated",
        "Jack Henry & Associates",
        "Jacobs Engineering Group",
        "J.B.Hunt Transport Services",
        "JM Smucker",
        "Johnson & Johnson",
        "Johnson Controls International",
        "JPMorgan Chase & Co.",
        "Juniper Networks",
        "Kansas City Southern",
        "Kellogg Co.",
        "KeyCorp",
        "Keysight Technologies",
        "Kimberly - Clark",
        "Kimco Realty",
        "Kinder Morgan",
        "KLA Corporation",
        "Kraft Heinz Co",
        "Kroger Co.",
        "L Brands Inc.",
        "L3Harris Technologies",
        "Laboratory Corp.of America Holding",
        "Lam Research",
        "Lamb Weston Holdings Inc",
        "Las Vegas Sands",
        "Leggett & Platt",
        "Leidos Holdings",
        "Lennar Corp.",
        "Lilly(Eli) & Co.",
        "Lincoln National",
        "Linde plc",
        "Live Nation Entertainment",
        "LKQ Corporation",
        "Lockheed Martin Corp.",
        "Loews Corp.",
        "Lowe's Cos.",
        "Lumen Technologies",
        "LyondellBasell",
        "M&T Bank",
        "Marathon Oil Corp.",
        "Marathon Petroleum",
        "MarketAxess",
        "Marriott International",
        "Marsh & McLennan",
        "Martin Marietta Materials",
        "Masco Corp.",
        "Mastercard Inc.",
        "McCormick & Co.",
        "Maxim Integrated Products",
        "McDonald's Corp.",
        "McKesson Corp.",
        "Medtronic plc",
        "Merck & Co.",
        "MetLife Inc.",
        "Mettler Toledo",
        "MGM Resorts International",
        "Microchip Technology",
        "Micron Technology",
        "Microsoft Corp.",
        "Mid - America Apartments",
        "Mohawk Industries",
        "Molson Coors Beverage Company",
        "Mondelez International",
        "Monolithic Power Systems",
        "Monster Beverage",
        "Moody's Corp",
        "Morgan Stanley",
        "The Mosaic Company",
        "Motorola Solutions Inc.",
        "MSCI Inc",
        "Nasdaq, Inc.",
        "NetApp",
        "Netflix Inc.",
        "Newell Brands",
        "Newmont Corporation",
        "News Corp (Class A)",
        "News Corp (Class B)",
        "NextEra Energy",
        "Nielsen Holdings",
        "Nike, Inc.",
        "NiSource Inc.",
        "Norfolk Southern Corp.",
        "Northern Trust Corp.",
        "Northrop Grumman",
        "NortonLifeLock",
        "Norwegian Cruise Line Holdings",
        "NOV Inc.",
        "NRG Energy",
        "Nucor Corp.",
        "Nvidia Corporation",
        "NVR, Inc.",
        "NXP Semiconductors",
        "O'Reilly Automotive",
        "Occidental Petroleum",
        "Old Dominion Freight Line",
        "Omnicom Group",
        "Oneok",
        "Oracle Corp.",
        "Otis Worldwide",
        "Paccar",
        "Packaging Corporation of America",
        "Parker - Hannifin",
        "Paychex Inc.",
        "Paycom",
        "PayPal",
        "Penn National Gaming",
        "Pentair plc",
        "People's United Financial",
        "PepsiCo Inc.",
        "PerkinElmer",
        "Perrigo",
        "Pfizer Inc.",
        "Philip Morris International",
        "Phillips 66",
        "Pinnacle West Capital",
        "Pioneer Natural Resources",
        "PNC Financial Services",
        "Pool Corporation",
        "PPG Industries",
        "PPL Corp.",
        "Principal Financial Group",
        "Procter & Gamble",
        "Progressive Corp.",
        "Prologis",
        "Prudential Financial",
        "Public Service Enterprise Group (PSEG)",
        "Public Storage",
        "PulteGroup",
        "PVH Corp.",
        "Qorvo",
        "Quanta Services Inc.",
        "Qualcomm",
        "Quest Diagnostics",
        "Ralph Lauren Corporation",
        "Raymond James Financial",
        "Raytheon Technologies",
        "Realty Income Corporation",
        "Regency Centers Corporation",
        "Regeneron Pharmaceuticals",
        "Regions Financial Corp.",
        "Republic Services Inc",
        "ResMed",
        "Robert Half International",
        "Rockwell Automation Inc.",
        "Rollins, Inc.",
        "Roper Technologies",
        "Ross Stores",
        "Royal Caribbean Group",
        "S&P Global Inc.",
        "Salesforce.com",
        "SBA Communications",
        "Schlumberger Ltd.",
        "Seagate Technology",
        "Sealed Air",
        "Sempra Energy",
        "ServiceNow",
        "Sherwin-Williams",
        "Simon Property Group Inc",
        "Skyworks Solutions",
        "Snap-on",
        "Southern Company",
        "Southwest Airlines",
        "Stanley Black & Decker",
        "Starbucks Corp.",
        "State Street Corp.",
        "Steris",
        "Stryker Corp.",
        "SVB Financial",
        "Synchrony Financial",
        "Synopsys Inc.",
        "Sysco Corp.",
        "T-Mobile US",
        "T. Rowe Price Group",
        "Take-Two Interactive",
        "Tapestry, Inc.",
        "Target Corp.",
        "TE Connectivity Ltd.",
        "Teledyne Technologies",
        "Teleflex",
        "Teradyne",
        "Tesla, Inc.",
        "Texas Instruments",
        "Textron Inc.",
        "Thermo Fisher Scientific",
        "TJX Companies Inc.",
        "Tractor Supply Company",
        "Trane Technologies plc",
        "TransDigm Group",
        "The Travelers Companies",
        "Trimble Inc.",
        "Truist Financial",
        "Twitter, Inc.",
        "Tyler Technologies",
        "Tyson Foods",
        "UDR, Inc.",
        "Ulta Beauty",
        "U.S. Bancorp",
        "Under Armour (Class A)",
        "Under Armour (Class C)",
        "Union Pacific Corp",
        "United Airlines Holdings",
        "UnitedHealth Group Inc.",
        "United Parcel Service",
        "United Rentals, Inc.",
        "Universal Health Services",
        "Unum Group",
        "Valero Energy",
        "Varian Medical Systems",
        "Ventas Inc",
        "Verisign Inc.",
        "Verisk Analytics",
        "Verizon Communications",
        "Vertex Pharmaceuticals Inc",
        "VF Corporation",
        "ViacomCBS",
        "Viatris",
        "Visa Inc.",
        "Vornado Realty Trust",
        "Vulcan Materials",
        "W. R. Berkley Corporation",
        "Westinghouse Air Brake Technologies Corp",
        "Walmart",
        "Walgreens Boots Alliance",
        "The Walt Disney Company",
        "Waste Management Inc.",
        "Waters Corporation",
        "WEC Energy Group",
        "Wells Fargo",
        "Welltower Inc.",
        "West Pharmaceutical Services",
        "Western Digital",
        "Western Union Co",
        "WestRock",
        "Weyerhaeuser",
        "Whirlpool Corp.",
        "Williams Companies",
        "Willis Towers Watson",
        "Wynn Resorts Ltd",
        "Xcel Energy Inc",
        "Xilinx",
        "Xylem Inc.",
        "Yum! Brands Inc",
        "Zebra Technologies",
        "Zimmer Biomet",
        "Zions Bancorp",
        "Zoetis",
    ],
};
