module.exports = {
    list: [
        "Abseling (Rappelling)",
        "Acrobatics",
        "Acroyoga",
        "Acting",
        "Aeromodelling",
        "Airbrushing",
        "Aircraft Spotting",
        "Airplane Combat",
        "Airplane Flight",
        "Airsofting",
        "Alligator Wrestling",
        "Amateur Astronomy",
        "Amateur Radio",
        "Animals/pets/dogs",
        "Ant Farm",
        "Aquarium (Freshwater & Saltwater)",
        "Archery",
        "Arts",
        "Astrology",
        "Astronomy",
        "Backgammon",
        "Badminton",
        "Barefooting",
        "Base Jumping",
        "Baseball",
        "Basketball",
        "Beach/Sun tanning",
        "Beachcombing",
        "Beadwork",
        "Beatboxing",
        "Becoming A Child Advocate",
        "Bell Ringing",
        "Belly Dancing",
        "Bicycle Polo",
        "Bird watching",
        "Birding",
        "Blacksmithing",
        "Blobbing",
        "Blogging",
        "BMX",
        "Board Games",
        "Boating",
        "Bobsledding",
        "Body Building",
        "Bonsai Tree",
        "Bookbinding",
        "Boomerangs",
        "Bowling",
        "Boxing",
        "Brewing Beer",
        "Bridge Building",
        "Bringing Food To The Disabled",
        "Building A House For Habitat For Humanity",
        "Building Dollhouses",
        "Bungee Jumping",
        "Butterfly Watching",
        "Button Collecting",
        "Cake Decorating",
        "Calligraphy",
        "Camping",
        "Candle Making",
        "Canoeing",
        "Canyon Swinging",
        "Car Racing",
        "Cardio Workout",
        "Cardstacking",
        "Cartooning",
        "Casino Gambling",
        "Cave Diving",
        "Ceramics",
        "Cheerleading",
        "Chess",
        "Church/church activities",
        "Cigar Smoking",
        "Cliff Diving",
        "Cloud Watching",
        "Coin Collecting",
        "Collecting",
        "Collecting Antiques",
        "Collecting Artwork",
        "Collecting Hats",
        "Collecting Music Albums",
        "Collecting RPM Records",
        "Collecting Sports Cards (Baseball, Football, Basketball, Hockey)",
        "Collecting Swords",
        "Coloring",
        "Compose Music",
        "Computer activities",
        "Contact Juggling",
        "Conworlding",
        "Cooking",
        "Cosplay",
        "Crafts",
        "Crafts (unspecified)",
        "Crochet",
        "Crocheting",
        "Cross-Stitch",
        "Crossword Puzzles",
        "Cycling",
        "Dancing",
        "Darts",
        "Diecast Collectibles",
        "Digital Photography",
        "Diving",
        "Dodgeball",
        "Dolls",
        "Dominoes",
        "Downhill Mountain Biking",
        "Downhill Skateboarding",
        "Drawing",
        "Dumpster Diving",
        "Eating out",
        "Educational Courses",
        "Electronics",
        "Embroidery",
        "Entertaining",
        "Exercise (aerobics, weights)",
        "Falconry",
        "Fast cars",
        "Felting",
        "Fencing",
        "Fire Poi",
        "Fishing",
        "Floorball",
        "Floral Arrangements",
        "Flowboarding",
        "Fly Fishing",
        "Fly Hunting",
        "Fly Tying",
        "Football",
        "Four Wheeling",
        "Free Climbing",
        "Freshwater Aquariums",
        "Frisbee Golf – Frolf",
        "Games",
        "Garage Saleing",
        "Gardening",
        "Genealogy",
        "Geocaching",
        "Ghost Hunting",
        "Glowsticking",
        "Gnoming",
        "Go Kart Racing",
        "Going to movies",
        "Golf",
        "Grip Strength",
        "Guitar",
        "Gun Collecting",
        "Gunsmithing",
        "Gymnastics",
        "Gyotaku",
        "Handwriting Analysis",
        "Hang gliding",
        "Herping",
        "Highlining",
        "Hiking",
        "Home Brewing",
        "Home Repair",
        "Home Theater",
        "Horseback Riding",
        "Hot air ballooning",
        "Hula Hooping",
        "Hunting",
        "Ice Climbing",
        "Ice Cross Downhill",
        "Ice Diving",
        "Ice Fishing",
        "Ice Skating",
        "Illusion",
        "Impersonations",
        "Inline Skating",
        "Internet",
        "Inventing",
        "Jet Engines",
        "Jetboarding",
        "Jewelry Making",
        "Jigsaw Puzzles",
        "Jousting",
        "Juggling",
        "Jump Roping",
        "Kayaking",
        "Keep A Journal",
        "Kitchen Chemistry",
        "Kite Boarding",
        "Kites",
        "Knitting",
        "Knotting",
        "Lacrosse",
        "Lasers",
        "Lawn Darts",
        "Learn to Play Poker",
        "Learning A Foreign Language",
        "Learning An Instrument",
        "Learning To Pilot A Plane",
        "Leathercrafting",
        "Legos",
        "Letterboxing",
        "Listening to music",
        "Locksport",
        "Luge / Skeleton",
        "Macramé",
        "Magic",
        "Making Model Cars",
        "Marksmanship",
        "Martial Arts",
        "Matchstick Modeling",
        "Meditation",
        "Metal Detecting",
        "Microscopy",
        "Model Railroading",
        "Model Rockets",
        "Modeling Ships",
        "Models",
        "Motocross",
        "Motorcycle Stunts",
        "Motorcycles",
        "Mountain Biking",
        "Mountain Boarding",
        "Mountain Climbing",
        "Musical Instruments",
        "Nail Art",
        "Needlepoint",
        "Noodling",
        "Off Road Driving",
        "Origami",
        "Owning An Antique Car",
        "Paintball",
        "Painting",
        "Papermache",
        "Papermaking",
        "Parachuting",
        "Paragliding or Power Paragliding",
        "Parkour",
        "People Watching",
        "Photography",
        "Piano",
        "Pilates",
        "Pinochle",
        "Pipe Smoking",
        "Planking",
        "Playing music",
        "Playing team sports",
        "Pole Dancing",
        "Pottery",
        "Powerboking",
        "Protesting",
        "Puppetry",
        "Pyrotechnics",
        "Quilting",
        "R/C Boats",
        "R/C Cars",
        "R/C Helicopters",
        "R/C Planes",
        "Racing Pigeons",
        "Rafting",
        "Rapping",
        "Reading",
        "Reading To The Elderly",
        "Renaissance Faire",
        "Rescuing Abused Or Abandoned Animals",
        "Robotics",
        "Rock Balancing",
        "Rock Climbing",
        "Rock Collecting",
        "Rockets",
        "Rocking AIDS Babies",
        "Roleplaying",
        "Roller Derby",
        "Running",
        "Running of the Bulls",
        "Sailing",
        "Saltwater Aquariums",
        "Sand Castles",
        "Sandboarding",
        "Scrapbooking",
        "Scuba Diving",
        "Self Defense",
        "Sewing",
        "Shark Diving",
        "Shark Fishing",
        "Shopping",
        "Singing In Choir",
        "Skateboarding",
        "Skeet Shooting",
        "Sketching",
        "Skiing",
        "Sky Diving",
        "Slack Lining",
        "Slingshots",
        "Slot Car Racing",
        "Snorkeling",
        "Snow Skiing",
        "Snowboarding",
        "Snowmobiling",
        "Soap Making",
        "Soccer",
        "Socializing",
        "Speed Cubing (rubix cube)",
        "Spelunkering",
        "Squash",
        "Stamp Collecting",
        "Storm Chasing",
        "Storytelling",
        "Street Luge",
        "String Figures",
        "Surf Fishing",
        "Surfing",
        "Survival",
        "Swimming",
        "Swimming",
        "Tai Chi",
        "Tatting",
        "Taxidermy",
        "Tea Tasting",
        "Tennis",
        "Tesla Coils",
        "Tetris",
        "Textiles",
        "Tombstone Rubbing",
        "Tool Collecting",
        "Toy Collecting",
        "Train Collecting",
        "Train Spotting",
        "Traveling",
        "Treasure Hunting",
        "Triathlon",
        "Tutoring Children",
        "Ultimate Frisbee",
        "Urban Exploration",
        "Video Games",
        "Violin",
        "Volunteer",
        "Wakeboarding",
        "Walking",
        "Warhammer",
        "Watching sporting events",
        "Water Ski",
        "Waterfall Kayaking",
        "Weightlifting",
        "White Water Rafting",
        "Windsurfing",
        "Wine Making",
        "Wingsuit Flying",
        "Woodworking",
        "Working In A Food Pantry",
        "Working on cars",
        "World Record Breaking",
        "Wrestling",
        "Writing",
        "Writing Music",
        "Writing Songs",
        "Xpogo",
        "Yoga",
        "YoYo",
        "Ziplining",
        "Zorbing",
        "Zumba",
    ],
};
